config/routes.rb
Rails.application.routes.draw do

   root 'products#index'

  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, :in_stock_qty, :price
  validates_numericality_of :in_stock_qty, :only_integer => true
  validates_numericality_of :price, :greater_than => 1

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    # @products = Product.all.page(params[:id]).per(10)
    @products = Product.page(params[:page]).per(10)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new

  end

  def create

  end

  def method_name

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1 class="container">index.html</h1>

<div class="container">
  <%= link_to 'New Post', new_product_path, :class=>"btn btn-danger" %>
</div>

<div class="container">
<% @products.each do |product| %>
<div class="products">
  <%= link_to product_path(product) do %>
    <%= image_tag(product.img_url, :width=>100) %> <br>
  <% end %>


<%= product.name %> <br>
<%= product.price %>
<br>
</div>
<% end %>
<!-- <div style="clear: both"></div> -->
<div class="clearfix"></div>
<%= paginate @products %>

</div>

app/views/products/show.html.erb
<h1 class="container"><%= @product.name %></h1>

<div class="container">
<%= image_tag(@product.img_url, :width => 50) %><br />

$<%= @product.price %>

<p>
<%= @product.description %>
</p>
</div>